config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'listings#index'

  resources :listings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :listing

  validates :listing, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show]

  def index
    @listings = Listing.all
  end

  def show
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Survey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Beds</th>
      <th>Baths</th>
      <th>Sale price</th>
      <th>Rent price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.beds %></td>
        <td><%= listing.baths %></td>
        <td><%= listing.sale_price %></td>
        <td><%= listing.rent_price %></td>
        <td><%= link_to 'Show', listing %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/listings/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Beds:</strong>
  <%= @listing.beds %>
</p>

<p>
  <strong>Baths:</strong>
  <%= @listing.baths %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @listing.sale_price %>
</p>

<p>
  <strong>Rent price:</strong>
  <%= @listing.rent_price %>
</p>

<p>
  <!--
    This part must be refactored into more appropiate approach.
  -->
  <%
    sum = 0.0
    avg = 0

    @listing.reviews.each do |review|
      sum += review.rating
    end
  %>
  <%
    if @listing.reviews.size != 0
      avg = sum / @listing.reviews.size
    end
  %>

  <strong> Average rating: </strong> <%= avg %>

</p>

<!--
  display rating box here or somewhere in this page.
-->

<%= link_to 'Back', listings_path %>